(function(){
const VERSION='v2026.06.25-patch5';
const DATA={metrics:{currentAccountBalance:0,sales2026:0,lifetimeSales:6531.60,lifetimeParking:2403.00,ticketActivity:4128.60},activeFunds:[{name:'Dennis',balance:0,rollForward:700,cashPaid:1124},{name:'Joel',balance:0,rollForward:700,cashPaid:1124},{name:'Kyle',balance:0,rollForward:310,cashPaid:1514},{name:'Dennis x 2',balance:0,rollForward:0,cashPaid:1824}],seatAccounts:[{seat:'Dennis Seat 1',owner:'Dennis',activeFrom:'2021',activeTo:'Current',balance:0},{seat:'Joel Seat',owner:'Joel',activeFrom:'2021',activeTo:'Current',balance:0},{seat:'Kyle Seat',owner:'Kyle',activeFrom:'2021',activeTo:'Current',balance:0},{seat:'Seth Seat',owner:'Seth',activeFrom:'2021',activeTo:'2025',balance:0},{seat:'Dennis Seat 2',owner:'Dennis',activeFrom:'2026',activeTo:'Current',balance:0}],parking:[{year:'2024',amount:1903.50},{year:'2025',amount:499.50},{year:'2026',amount:0}],history:[{season:'2021',record:'2-10',games:12,note:''},{season:'2022',record:'4-8',games:12,note:''},{season:'2023',record:'3-9',games:12,note:''},{season:'2024',record:'11-2',games:13,note:'CFP first round'},{season:'2025',record:'16-0',games:16,note:'🏆 National Champions'},{season:'2026',record:'0-0',games:12,note:'Upcoming'}],postseason2025:[{date:'2025-12-06',game:'Ohio State · Lucas Oil Stadium',result:'W 13-10',flag:'Big Ten Championship; Postseason'},{date:'2026-01-01',game:'Alabama · Rose Bowl',result:'W 38-3',flag:'Rose Bowl; CFP; Postseason'},{date:'2026-01-09',game:'Oregon · Mercedes-Benz Stadium',result:'W 56-22',flag:'Peach Bowl; CFP Semifinal; Postseason'},{date:'2026-01-19',game:'Miami (FL) · Hard Rock Stadium',result:'W 27-21',flag:'CFP National Championship; Postseason'}]};
const screens=[['score','🏟️','Score'],['money','💰','Money'],['seats','🎟️','Seats'],['parking','🅿️','Parking'],['history','🏆','History'],['settle','🤝','Settle'],['manager','✍️','Manager']];
let current='score';
const $=s=>document.querySelector(s); const money=n=>'$'+Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}); const money0=n=>'$'+Math.round(Number(n||0)).toLocaleString('en-US');
function setMode(){const c=window.HTCC_CONFIG||{}; const graph=(c.authMode==='graph'||c.graphEnabled===true); const ready=window.HTCC_GRAPH&&window.HTCC_GRAPH.msalReady&&window.HTCC_GRAPH.msalReady(); $('#dataMode').textContent= graph ? (ready?'Graph configured':'Graph configured - MSAL blocked') : 'Fallback JSON'; $('#version').textContent=VERSION;}
function card(title,val,sub,cls=''){return `<article class="card"><h3>${title}</h3><div class="value ${cls}">${val}</div><div class="sub">${sub||''}</div></article>`;}
function notice(html,cls=''){return `<div class="notice ${cls}">${html}</div>`;}
function table(headers,rows){return `<div class="table"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td class="${i>0?'num':''}">${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function layout(eyebrow,title,lede,body){$('#app').innerHTML=`${notice('<b>Privacy flag:</b> this app displays real financial data. Host the app safely and keep the workbook/JSON private.')}<section><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><p class="lede">${lede}</p>${body}</section>`;}
function renderScore(){const m=DATA.metrics, f=DATA.activeFunds; layout('Scoreboard','Game Day Dashboard','Current values are active 2026 fund balances. Historical activity is shown separately so old sales do not pretend to be cash on hand.',`<div class="grid">${card('Current Account Balance',money(m.currentAccountBalance),'2026 active ledger')}${card('2026 Sales Logged',money(m.sales2026),'new season activity')}${card('Lifetime Sales Handled',money0(m.lifetimeSales),'2024 + 2025 regular sales')}${card('Parking Handled',money0(m.lifetimeParking),'tracked separately from seats')}</div><p class="eyebrow" style="margin-top:26px">Active Funds</p><div class="grid">${f.map(x=>`<article class="card"><h3>${x.name}</h3><div class="value">${money(x.balance)}</div><div class="line"><span>Roll-forward</span><b>${money(x.rollForward)}</b></div><div class="line"><span>2026 cash paid</span><b>${money(x.cashPaid)}</b></div></article>`).join('')}</div>${notice('<b>Source of truth:</b> Excel workbook in OneDrive remains official until Microsoft Graph writeback is live. New 2026 sales/purchases will change these balances.')}`);}
function renderMoney(){const m=DATA.metrics; layout('Money','Hoosier Fund Moneyline','Money is split into current active balance, historical sales handled, ticket activity, and parking activity.',`<div class="grid two">${card('Current Active Balance',money(m.currentAccountBalance),'cash currently held for 2026 active ledger')}${card('2026 Sales Logged',money(m.sales2026),'new 2026 activity')}${card('Lifetime Regular Sales',money(m.lifetimeSales),'2024 + 2025 handled through the ledger')}${card('Ticket Activity',money(m.ticketActivity),'tickets only, parking removed')}${card('Parking Activity',money(m.lifetimeParking),'member-level parking split')}${card('Settlement If Closed Today',money(m.currentAccountBalance),'based on active ledger assumption')}</div>${notice('<b>Rule:</b> current balance and lifetime activity are intentionally separate. Old sales are history unless they rolled forward into current funds.')}`);}
function renderSeats(){layout('Seats','Seat Standings','Each ticket is treated as its own seat account. Dennis Seat 2 replaces the former fourth seat in 2026.',`<div class="grid">${DATA.seatAccounts.filter(s=>s.activeTo==='Current').map(s=>card(s.seat,money(s.balance),`Owner: ${s.owner}`)).join('')}</div><p class="eyebrow" style="margin-top:26px">Seat Accounts</p>${table(['Seat','Owner','Active From','Active To'],DATA.seatAccounts.map(s=>[s.seat,s.owner,s.activeFrom,s.activeTo]))}`);}
function renderParking(){const total=DATA.parking.reduce((a,p)=>a+p.amount,0); layout('Parking','Parking Pass Tracker','Parking is separate from game tickets and allocated at the member level, not the seat level.',`<div class="grid">${DATA.parking.map(p=>card(`${p.year} Parking`,money(p.amount),p.amount?'member-level split':'nothing yet')).join('')}${card('Lifetime Parking',money(total),'total handled')}</div>`);}
function renderHistory(){layout('Hoosier History','Season Rewind','History gives the dashboard some soul, but it stays separate from the accounting ledger.',`${table(['Season','Record','Games','Note'],DATA.history.map(h=>[h.season,h.record,h.games,h.note]))}<p class="eyebrow" style="margin-top:26px">2025 Championship Run</p>${table(['Date','Game','Result','Flag'],DATA.postseason2025.map(g=>[g.date,g.game,g.result,g.flag]))}`);}
function renderSettle(){layout('Settlement','Settlement Snapshot','If the shared account were closed today, this is what each active fund would receive based on the active 2026 ledger.',`${table(['Fund','Settlement'],DATA.activeFunds.map(f=>[f.name,money(f.balance)]))}${notice('<b>Assumption:</b> actual bank balance equals calculated ledger balance. No separate bank reconciliation field is included yet.')}`);}
function renderManager(){layout('Manager','Manager Entry Roadmap','For now, Excel stays official. After Microsoft Graph is fully wired, this screen will append rows to the Transactions table in OneDrive.',`<div class="card"><div class="form"><label>Transaction date<input type="date" id="txDate"></label><label>Asset type<select id="txAsset"><option>Game Ticket</option><option>Parking</option><option>Fee</option><option>Adjustment</option></select></label><label>Amount<input id="txAmount" type="number" step="0.01" placeholder="0.00"></label><label>Owner / split<select id="txOwner"><option>All Members</option><option>Dennis</option><option>Joel</option><option>Kyle</option><option>Dennis x 2</option></select></label><label class="wide">Description<textarea id="txDesc" placeholder="Example: IU vs Purdue parking resale"></textarea></label></div><p><button class="btn" id="previewBtn">Preview row</button> <button class="btn" id="appendBtn">Append to OneDrive table</button></p><pre class="notice" id="previewBox">No row preview yet.</pre></div>`); setTimeout(()=>{const b=$('#previewBtn'); if(b)b.onclick=()=>{$('#previewBox').textContent=JSON.stringify({date:$('#txDate').value,assetType:$('#txAsset').value,amount:Number($('#txAmount').value||0),owner:$('#txOwner').value,description:$('#txDesc').value},null,2)}; const a=$('#appendBtn'); if(a)a.onclick=()=>alert('Writeback is staged. Next step: map workbook table columns and enable append.');},0);}
const renderers={score:renderScore,money:renderMoney,seats:renderSeats,parking:renderParking,history:renderHistory,settle:renderSettle,manager:renderManager};
function show(id){try{current=id; document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.screen===id)); (renderers[id]||renderScore)();}catch(err){console.error('HTCC render failure',id,err); $('#app').innerHTML=`<section><p class="eyebrow">App error</p><h2>Something failed to render</h2>${notice('<b>Error:</b> '+(err&&err.message?err.message:String(err)),'danger')}</section>`;}}
function init(){try{setMode(); const n=$('#bottomNav'); n.innerHTML=screens.map(([id,icon,label])=>`<button class="navbtn" data-screen="${id}"><span>${icon}</span>${label}</button>`).join(''); n.onclick=e=>{const b=e.target.closest('button[data-screen]'); if(b)show(b.dataset.screen);}; const cb=$('#connectBtn'); if(cb) cb.onclick=async()=>{try{if(!window.HTCC_GRAPH) throw new Error('Graph client not loaded'); const res=await window.HTCC_GRAPH.connect(); $('#dataMode').textContent='OneDrive connected'; alert('Connected as '+((res.account&&res.account.username)||'Microsoft account'));}catch(e){alert(e.message||String(e));}}; show('score');}catch(e){console.error(e); $('#app').innerHTML=`<div class="notice danger"><b>Startup failed:</b> ${e.message||String(e)}</div>`;}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
